export type Theme = {
  id: string;
  label: string;
  mode: "dark" | "light";
  bg: string;
  fg: string;
  prompt: string;
  cmd: string;
  output: string;
  accent: string;
  green: string;
};

export const THEMES: Theme[] = [
  {
    id: "tokyonight",
    label: "tokyo night",
    mode: "dark",
    bg: "#1a1b26",
    fg: "#c0caf5",
    prompt: "#ff7edb",
    cmd: "#c0caf5",
    output: "#9eceff",
    accent: "#7aa2f7",
    green: "#9ece6a",
  },
  {
    id: "dracula",
    label: "dracula",
    mode: "dark",
    bg: "#282a36",
    fg: "#f8f8f2",
    prompt: "#ff79c6",
    cmd: "#f8f8f2",
    output: "#8be9fd",
    accent: "#bd93f9",
    green: "#50fa7b",
  },
  {
    id: "github-dark",
    label: "github dark",
    mode: "dark",
    bg: "#0d1117",
    fg: "#e6edf3",
    prompt: "#ff7b72",
    cmd: "#e6edf3",
    output: "#79c0ff",
    accent: "#d2a8ff",
    green: "#7ee787",
  },
  {
    id: "gruvbox",
    label: "gruvbox",
    mode: "dark",
    bg: "#282828",
    fg: "#ebdbb2",
    prompt: "#fb4934",
    cmd: "#ebdbb2",
    output: "#83a598",
    accent: "#fabd2f",
    green: "#b8bb26",
  },
  {
    id: "catppuccin-mocha",
    label: "catppuccin mocha",
    mode: "dark",
    bg: "#1e1e2e",
    fg: "#cdd6f4",
    prompt: "#cba6f7",
    cmd: "#cdd6f4",
    output: "#89b4fa",
    accent: "#89b4fa",
    green: "#a6e3a1",
  },
  {
    id: "nord",
    label: "nord",
    mode: "dark",
    bg: "#2e3440",
    fg: "#d8dee9",
    prompt: "#88c0d0",
    cmd: "#d8dee9",
    output: "#81a1c1",
    accent: "#5e81ac",
    green: "#a3be8c",
  },
  {
    id: "one-dark",
    label: "one dark",
    mode: "dark",
    bg: "#282c34",
    fg: "#abb2bf",
    prompt: "#c678dd",
    cmd: "#abb2bf",
    output: "#61afef",
    accent: "#61afef",
    green: "#98c379",
  },
  {
    id: "solarized-dark",
    label: "solarized dark",
    mode: "dark",
    bg: "#002b36",
    fg: "#839496",
    prompt: "#d33682",
    cmd: "#93a1a1",
    output: "#268bd2",
    accent: "#2aa198",
    green: "#859900",
  },
  {
    id: "github-light",
    label: "github light",
    mode: "light",
    bg: "#ffffff",
    fg: "#1f2328",
    prompt: "#cf222e",
    cmd: "#1f2328",
    output: "#0969da",
    accent: "#8250df",
    green: "#1a7f37",
  },
  {
    id: "solarized-light",
    label: "solarized light",
    mode: "light",
    bg: "#fdf6e3",
    fg: "#657b83",
    prompt: "#d33682",
    cmd: "#586e75",
    output: "#268bd2",
    accent: "#2aa198",
    green: "#859900",
  },
  {
    id: "one-light",
    label: "one light",
    mode: "light",
    bg: "#fafafa",
    fg: "#383a42",
    prompt: "#a626a4",
    cmd: "#383a42",
    output: "#4078f2",
    accent: "#0184bc",
    green: "#50a14f",
  },
  {
    id: "catppuccin-latte",
    label: "catppuccin latte",
    mode: "light",
    bg: "#eff1f5",
    fg: "#4c4f69",
    prompt: "#8839ef",
    cmd: "#4c4f69",
    output: "#1e66f5",
    accent: "#209fb5",
    green: "#40a02b",
  },
  {
    id: "gruvbox-light",
    label: "gruvbox light",
    mode: "light",
    bg: "#fbf1c7",
    fg: "#3c3836",
    prompt: "#9d0006",
    cmd: "#3c3836",
    output: "#076678",
    accent: "#b57614",
    green: "#79740e",
  },
];

export function getTheme(id: string): Theme {
  return THEMES.find((t) => t.id === id) ?? THEMES[0];
}
